# safelist
branches:
  only:
    - system_python

dist: trusty
language: python
group: edge

python:
  - "3.6"
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - SERVICE1="diana"
    - SERVICE2="diana-learn"

  matrix:
    - ARCH_TAG="amd64"
    - ARCH_TAG="arm32v7" SERVICE3="diana-movidius"
    - ARCH_TAG="arm64v8"

before_install:

  # Put docker into "experimental" for manifest function
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' > "$HOME/.docker/config.json"

  - pip3 install pyyaml  # for manifest-it

    # Register qemu as cross-compiler
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

install:

  # Build image
  - docker-compose build $SERVICE1-$ARCH_TAG
  - docker-compose build $SERVICE2-$ARCH_TAG
  - '["$SERVICE3"] && docker-compose build $SERVICE3-$ARCH_TAG || echo "No SERVICE3 defined"'

script: true

#  - (docker run --rm derekmerck/diana:$ARCH_TAG python3 /opt/diana/apps/cli/clf_chest_pose.py -m /opt/diana/tests/resources/chest_cr/pose_weights.h5 -d /opt/diana/tests/resources/chest_cr/CR01.dcm 2> /dev/null ) | grep -q FRONTAL
#
#  - (docker run --rm derekmerck/diana:$ARCH_TAG python3 /opt/diana/apps/cli/clf_chest_pose.py -m /opt/diana/tests/resources/chest_cr/pose_weights.h5 -d /opt/diana/tests/resources/chest_cr/CR00.dcm 2> /dev/null ) | grep -q LATERAL

after_success:

  # Login to docker for push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # manifest and push
  - python3 manifest-it.py diana-xarch.manifest.yml
