# xArch Diana-Learn System Python Image
# Derek Merck, Summer 2018

ARG ARCH_TAG="arm64v8"

FROM derekmerck/diana:${ARCH_TAG}
MAINTAINER Derek Merck <derek_merck@brown.edu>

RUN apt update \
    && apt upgrade \
    && apt install -y --no-install-recommends \
        python3-scipy \
        python3-h5py \
        python3-protobuf \
        python3-numpy-dev \
        python3-cffi \
        cython3 \
        libhdf5-dev \
        libatlas-base-dev \
        libopenblas-dev \
        gfortran \
    && apt clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-deps --no-cache-dir -U \
        scipy \
        pydot \
        h5py \
        protobuf \
        absl-py \
        pyparsing

ENV KERAS_BACKEND=tensorflow

# Local buid
COPY tensorflow-1.9.0rc0-cp35-cp35m-linux_aarch64.whl /tmp

# Remote build
#RUN curl -L -o /tmp/tensorflow-1.9.0rc0-cp35-cp35m-linux_aarch64.whl https://www.dropbox.com/s/pmijwdx0iv5mcv2/tensorflow-1.9.0rc0-cp35-cp35m-linux_aarch64.whl?dl=1

# --no-cache-dir

RUN pip install --no-deps /tmp/tensorflow-1.9.0rc0-cp35-cp35m-linux_aarch64.whl \
    && rm /tmp/tensorflow-1.9.0rc0-cp35-cp35m-linux_aarch64.whl

RUN pip3 install --no-deps --no-cache-dir \
        keras
