version: '3'

services:

  # ---------------------------
  # diana base image
  #   - conda py3.7
  #   - diana
  # ---------------------------

  diana-conda-amd64:
    build:
      context: conda-python
    image: diana-conda-amd64

  diana-conda-arm32v7:
    build:
      context: conda-python
    image: diana-conda-amd64

  # ---------------------------
  # diana base image
  #   - system py3.5
  #   - diana
  # ---------------------------

  diana-amd64:
    build:
      context: system-python/diana
    image: diana-amd64

  diana-arm32v7:
    build:
      context: system-python/diana
      args:
        RESIN_ARCH:   armv7hf
        DOCKER_ARCH:  arm32v7
    image: diana-arm32v7

  diana-arm64v8:
    build:
      context: system-python/diana
      args:
        RESIN_ARCH:   aarch64
        DOCKER_ARCH:  arm64v8
    image: diana-arm64v8


  # ---------------------------
  # diana learn image
  #   - system py3.5
  #   - tensorflow
  #   - keras
  #   - diana
  # ---------------------------

  diana-learn-amd64:
    build:
      context: system-python/diana-learn
    image: diana-learn-amd64

  diana-learn-arm32v7:
    build:
      context: system-python/diana-learn
      args:
        DOCKER_ARCH: arm32v7
    image: diana-learn-arm32v7

  diana-learn-arm64v8:
    build:
      context: system-python/diana-learn
      dockerfile: Dockerfile-arm64v8
      args:
        DOCKER_ARCH: arm64v8
    image: diana-learn-arm64v8


  # ---------------------------
  # diana learn image
  #   - system py3.5, py2.7
  #   - tensorflow
  #   - keras
  #   - ncsdk2
  #   - diana
  # ---------------------------

  diana-movidius-arm32v7:
    build:
      context: system-python/diana-movidius
      args:
        DOCKER_ARCH: arm32v7
    image: diana-movidius-arm32v7
