version: '3'

services:

  # ---------------------------
  # diana base image
  #   - conda py3.7
  #   - diana
  # ---------------------------

  diana-conda-amd64:
    build:
      context: conda-python
    image: diana-conda-amd64

  diana-conda-arm32v7:
    build:
      context: conda-python
    image: diana-conda-amd64

  # ---------------------------
  # diana base image
  #   - system py3.5
  #   - diana
  # ---------------------------

  diana-amd64:
    build:
      context: system-python/diana
    image: diana-amd64

  diana-arm32v7:
    build:
      context: system-python/diana
      args:
        RESIN_ARCH:   armv7hf
        DOCKER_ARCH:  arm32v7
    image: diana-arm32v7

  diana-arm64v8:
    build:
      context: system-python/diana
      args:
        RESIN_ARCH:   aarch64
        DOCKER_ARCH:  arm64v8
    image: diana-arm64v8


  # ---------------------------
  # diana ai image
  #   - system py3.5
  #   - tensorflow
  #   - keras
  #   - diana
  # ---------------------------

  diana-ai-amd64:
    build:
      context: system-python/diana-ai
    image: diana-ai-amd64

  diana-ai-arm32v7:
    build:
      context: system-python/diana-ai
      dockerfile: Dockerfile-dl
      args:
        DOCKER_ARCH: arm32v7
        TF_URL:   https://storage.googleapis.com/tensorflow-nightly
        TF_WHEEL: tensorflow-1.10.0-cp34-none-linux_armv7l.whl
    image: diana-ai-arm32v7

  diana-ai-arm64v8:
    build:
      context: system-python/diana-ai
      dockerfile: Dockerfile-dl
      args:
        DOCKER_ARCH: arm64v8
        TF_URL: https://www.dropbox.com/s/svovlw463xe64u3
        TF_WHEEL: tensorflow-1.11.0rc1-cp35-cp35m-linux_aarch64.whl
    image: diana-ai-arm64v8


  # ---------------------------
  # diana learn image
  #   - system py3.5, py2.7
  #   - tensorflow
  #   - keras
  #   - ncsdk2
  #   - diana
  # ---------------------------

  diana-movidius-arm32v7:
    build:
      context: system-python/diana-movidius
      args:
        DOCKER_ARCH: arm32v7
    image: diana-movidius-arm32v7
