version: '3'

services:

  diana-amd64:
    build:
      context: .
    image: derekmerck/diana:amd64

  diana-arm32v7:
    build:
      context: .
      args:
        RESIN_ARCH: raspberrypi3
    image: derekmerck/diana:arm32v7

  diana-arm64v8:
    build:
      context: .
      dockerfile: Dockerfile-arm64
      args:
        RESIN_ARCH: jetson-tx2
    image: derekmerck/diana:arm64v8
